### ISSUE TITLE
Symbolize and Split Dataset步骤时遇到了KeyError: 'code_sym_token'

### ISSUE THREAD

**Issue by Jones-match** [jumormt/DeepWukong#19]
(wukong) root@autodl-container-46914989bd-be6f2b06:~/autodl-tmp/v3/v3wukong# PYTHONPATH="." python src/preprocess/dataset_generator.py
/root/miniconda3/envs/wukong/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
Global seed set to 7
testcases: 100%|██████████████████████████████████████████████████████████████| 20175/20175 [17:35<00:00, 19.11it/s]
total 999630 XFGs!
xfgs:   0%|▎                                                               | 4930/1005201 [00:00<02:00, 8322.60it/s]
Traceback (most recent call last):
  File "src/preprocess/dataset_generator.py", line 176, in <module>
    xfg_unique_paths = unique_data(config.dataset.name, config.data_folder)
  File "src/preprocess/dataset_generator.py", line 51, in unique_data
    xfg_dict = unique_xfg_sym(xfg_paths)
  File "/root/autodl-tmp/v3/v3wukong/src/utils.py", line 141, in unique_xfg_sym
    ln_md5 = getMD5(str(xfg.nodes[ln]["code_sym_token"]))
KeyError: 'code_sym_token'

在第一步可以使用PDG正常生成XFG， 但在第二步的时候，还是会出现找不到code_sym_token属性。想请教一下应该如何解决

**Comment by mcf20** [comment]
> （wukong） root@autodl-container-46914989bd-be6f2b06：~/autodl-tmp/v3/v3wukong# PYTHONPATH=“.” python src/preprocess/dataset_generator.py /root/miniconda3/envs/wukong/lib/python3.8/site-packages/pytorch_lightning/metrics/**init**.py：43：LightningDeprecationWarning：自 v1.3 以来，模块已重命名并拆分为自己的包 （https://github.com/PyTorchLightning/metrics），并将在 v1.5 rank_zero_deprecation（全局种子集为 7 个测试用例：100%|██████████████████████████████████████████████████████████████|20175/20175 [17：35<00：00， 19.11it/s] 共 999630 XFGs！ xfgs： 0%|▎ |4930/1005201 [00：00<02：00， 8322.60it/s] 回溯 （最近一次调用最后一次） ： 文件“src/preprocess/dataset_generator.py”，第 176 行，xfg_unique_paths = unique_data（config.dataset.name，config.data_folder） 文件“src/preprocess/dataset_generator.py”，第 51 行，unique_data xfg_dict = unique_xfg_sym（xfg_paths） 文件“/root/autodl-tmp/v3/v3wukong/src/utils.py”，第 141 行，unique_xfg_symln_md5 = getMD5（str（xfg.nodes[ln][“code_sym_token”]）） KeyError： 'code_sym_token'`pytorch_lightning.metrics.*``torchmetrics.*`
> 
> 在第一步可以使用PDG正常生成XFG， 但在第二步的时候，还是会出现找不到code_sym_token属性。想请教一下应该如何解决

想请问一下您 这个项目环境怎么部署呢 尤其是joern那  感谢您的回复！！！！！

**Comment by Jones-match** [comment]
joern 是直接在README.md 中给出的地址下载的源码https://github.com/ives-nx/dwk_preprocess/tree/main/joern_slicer/joern

在将joern的源码下载后，复制到wukong 项目的根目录下
然后将根目录下的./config/dwk.yaml 中的joern_path 修改
```yaml
# preprocess keys
joern_path: "/root/autodl-tmp/v3/v3wukong/dwk_preprocess-main/joern_slicer/joern/joern-parse"
split_token: false
```
修改这些之后运行项目

------
不知道是否缺少了其他配置步骤，希望得到老师指点

**Comment by mcf20** [comment]
> joern 是直接在 README.md 中给出的地址下载的源码 https://github.com/ives-nx/dwk_preprocess/tree/main/joern_slicer/joern
> 
> 在将joern的源码下载后，复制到wukong 项目的根目录下 然后将根目录下的./config/dwk.yaml 中的joern_path 修改
> 
> ```yaml
> # preprocess keys
> joern_path: "/root/autodl-tmp/v3/v3wukong/dwk_preprocess-main/joern_slicer/joern/joern-parse"
> split_token: false
> ```
> 
> 修改这些之后运行项目
> 
> 不知道是否缺少了其他配置步骤，希望得到老师指点

感谢您的回复  这是在ubuntu里面跑的么

**Comment by Jones-match** [comment]
是的，ubuntu18.04   cuda11.1

**Comment by mcf20** [comment]
> 是的，ubuntu18.04 cuda11.1

服务器还是虚拟机呢

**Comment by mcf20** [comment]
> 是的，ubuntu18.04 cuda11.1

方便加个联系方式么 想咨询一下问题

**Comment by Jones-match** [comment]
服务器
----------

lsq163@126.com

**Comment by 664730** [comment]
> (wukong) root@autodl-container-46914989bd-be6f2b06:~/autodl-tmp/v3/v3wukong# PYTHONPATH="." python src/preprocess/dataset_generator.py /root/miniconda3/envs/wukong/lib/python3.8/site-packages/pytorch_lightning/metrics/**init**.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5 rank_zero_deprecation( Global seed set to 7 testcases: 100%|██████████████████████████████████████████████████████████████| 20175/20175 [17:35<00:00, 19.11it/s] total 999630 XFGs! xfgs: 0%|▎ | 4930/1005201 [00:00<02:00, 8322.60it/s] Traceback (most recent call last): File "src/preprocess/dataset_generator.py", line 176, in xfg_unique_paths = unique_data(config.dataset.name, config.data_folder) File "src/preprocess/dataset_generator.py", line 51, in unique_data xfg_dict = unique_xfg_sym(xfg_paths) File "/root/autodl-tmp/v3/v3wukong/src/utils.py", line 141, in unique_xfg_sym ln_md5 = getMD5(str(xfg.nodes[ln]["code_sym_token"])) KeyError: 'code_sym_token'
> 
> 在第一步可以使用PDG正常生成XFG， 但在第二步的时候，还是会出现找不到code_sym_token属性。想请教一下应该如何解决

请问 KeyError: 'code_sym_token'这个问题您解决了吗？

**Comment by bysota** [comment]
#USE_CPU = cpu_count()
USE_CPU = 2

**Comment by THDGunner** [comment]
> > (wukong) root@autodl-container-46914989bd-be6f2b06:~/autodl-tmp/v3/v3wukong# PYTHONPATH="." python src/preprocess/dataset_generator.py /root/miniconda3/envs/wukong/lib/python3.8/site-packages/pytorch_lightning/metrics/**init**.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5 rank_zero_deprecation( Global seed set to 7 testcases: 100%|██████████████████████████████████████████████████████████████| 20175/20175 [17:35<00:00, 19.11it/s] total 999630 XFGs! xfgs: 0%|▎ | 4930/1005201 [00:00<02:00, 8322.60it/s] Traceback (most recent call last): File "src/preprocess/dataset_generator.py", line 176, in xfg_unique_paths = unique_data(config.dataset.name, config.data_folder) File "src/preprocess/dataset_generator.py", line 51, in unique_data xfg_dict = unique_xfg_sym(xfg_paths) File "/root/autodl-tmp/v3/v3wukong/src/utils.py", line 141, in unique_xfg_sym ln_md5 = getMD5(str(xfg.nodes[ln]["code_sym_token"])) KeyError: 'code_sym_token'
> > 在第一步可以使用PDG正常生成XFG， 但在第二步的时候，还是会出现找不到code_sym_token属性。想请教一下应该如何解决
> 
> 请问 KeyError: 'code_sym_token'这个问题您解决了吗？

hello,请问KeyError: 'code_sym_token'这个问题解决了吗？

**Comment by zhaobosen** [comment]
> (wukong) root@autodl-container-46914989bd-be6f2b06:~/autodl-tmp/v3/v3wukong# PYTHONPATH="." python src/preprocess/dataset_generator.py /root/miniconda3/envs/wukong/lib/python3.8/site-packages/pytorch_lightning/metrics/**init**.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5 rank_zero_deprecation( Global seed set to 7 testcases: 100%|██████████████████████████████████████████████████████████████| 20175/20175 [17:35<00:00, 19.11it/s] total 999630 XFGs! xfgs: 0%|▎ | 4930/1005201 [00:00<02:00, 8322.60it/s] Traceback (most recent call last): File "src/preprocess/dataset_generator.py", line 176, in xfg_unique_paths = unique_data(config.dataset.name, config.data_folder) File "src/preprocess/dataset_generator.py", line 51, in unique_data xfg_dict = unique_xfg_sym(xfg_paths) File "/root/autodl-tmp/v3/v3wukong/src/utils.py", line 141, in unique_xfg_sym ln_md5 = getMD5(str(xfg.nodes[ln]["code_sym_token"])) KeyError: 'code_sym_token'
> 
> 在第一步可以使用PDG正常生成XFG， 但在第二步的时候，还是会出现找不到code_sym_token属性。想请教一下应该如何解决

请问为什么我运行data_generator后生成0个XFG呢？您有遇到过类似情况吗
